service:
  name: citypantry-error-plugin

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  memorySize: 256
  profile: citypantry

functions:
  report:
    handler: handler.report
    events:
      - http:
          method: post
          path: report

custom:
  webpack:
    mode: development
