service:
  name: citypantry-error-plugin

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  webpack:
    mode: development
  bucket: citypantry-bug-screenshots

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  memorySize: 256
  profile: citypantry
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  report:
    handler: handler.report
    events:
      - http:
          method: post
          path: report
